server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.75.100:3306/myforum
    username: root
    password: hjh123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 1017165985@qq.com
    password: oajccsvhlulobeja
    protocol: smtps
    properties:
      mail.stmp.ssl.enable: true
  redis:
    port: 6379
    host: 192.168.75.100
    password: hjh123123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 100000
    database: 1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    Myforum.mapper: debug

MyForum:
  path:
    domain: http://localhost:8080